{{- $enabled_configmap := .Values.configmap.enabled }}

{{- if $enabled_configmap }}
  {{- range $configmap := .Values.configmap.configs }}
---
apiVersion: v1
data:
  {{ $configmap.filename }}: |
{{ toYaml $configmap.file_content | indent 4 }}
kind: ConfigMap
metadata:
  name: {{ $configmap.name }}
  namespace: {{ $configmap.namespace }}
  labels:
    name: {{ $configmap.name }}
  {{- end }}
{{- end }}
