{{- $enabled_cronjob := .Values.cronjob.enabled }}
{{- $enabled_istio := .Values.istio.enabled }}

{{- if eq .Values.arch "cronjob" }}
  {{- $enabled_cronjob = true }}
{{- end }}

{{- if $enabled_cronjob }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: {{ .Values.pod.iam_role }}
            sidecar.istio.io/inject: "{{ $enabled_istio }}"
          labels:
{{- if .Values.labels }}{{- range $name, $value := .Values.labels }}{{- if not (empty $value) }}
            {{ $name }}: {{ $value }}
{{- end }}{{- end }}{{- else }}
            name: {{ .Values.name }}
{{- end }}
        spec:
          containers:
          - command:
{{- range $cmd := .Values.pod.command }}
            - {{ $cmd }}
{{- end }}
            env:
{{- range $name, $value := .Values.pod.env }}{{- if not (empty $value) }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
{{- end }}{{- end }}
            image: {{ .Values.pod.image_name }}:{{ .Values.pod.image_tag }}
            imagePullPolicy: {{ .Values.pod.imagePullPolicy }}
            name: {{ .Values.name }}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: {{ .Values.pod.dnsPolicy }}
          restartPolicy: {{ .Values.pod.restartPolicy }}
          schedulerName: {{ .Values.pod.schedulerName }}
          terminationGracePeriodSeconds: {{ .Values.pod.terminationGracePeriodSeconds }}
  schedule: {{ .Values.cronjob.schedule | quote }}
{{- if .Values.cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
{{- end }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  suspend: {{ .Values.cronjob.suspend }}
{{- end }}
