{{ if .Values.externalSecrets.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
    {{ if .Values.externalSecrets.app.nameOverride }}
    name: {{ .Values.externalSecrets.app.name }}
    {{ else }}
    name: {{ .Values.externalSecrets.app.name }}-{{ .Values.externalSecrets.environment.name }}-secret
    {{ end }}
    {{ if .Values.externalSecrets.app.namespace }}
    namespace: {{ .Values.externalSecrets.app.namespace }}
    {{ else }}
    namespace: {{ .Values.externalSecrets.app.name }}-{{ .Values.externalSecrets.environment.name }}
    {{ end }}
    {{ if .Values.externalSecrets.annotations }}
    annotations:
        {{- range $name, $value := .Values.externalSecrets.projection.annotations }}
        {{- if not (empty $value) }}
        {{ $name }}: {{ $value }}
        {{- end }}
        {{- end }}
    {{ end }}
    {{ if .Values.externalSecrets.labels }}
    labels:
        {{- range $name, $value := .Values.externalSecrets.projection.labels }}
        {{- if not (empty $value) }}
        {{ $name }}: {{ $value }}
        {{- end }}
        {{- end }}
    {{ end }}
spec:
    {{ if eq .Values.externalSecrets.backend.type "secretsManager" }}
    backendType: secretsManager
    roleArn: arn:aws:iam::{{ toString .Values.externalSecrets.backend.aws.accountID }}:role/{{ .Values.externalSecrets.backend.aws.roleName }}
    region: {{ .Values.externalSecrets.backend.aws.region }}
    {{ end }}
    {{ if eq .Values.externalSecrets.backend.type "gcpSecretsManager" }}
    backendType: gcpSecretsManager
    projectId: {{ .Values.externalSecrets.backend.projectID }}
    {{ end }}
    {{ if.Values.externalSecrets.data }}
    data: {{ toYaml .Values.externalSecrets.data | nindent 8 }}
    {{ end }}
    {{ if .Values.externalSecrets.dataFrom }}
    dataFrom: {{ toYaml .Values.externalSecrets.dataFrom | nindent 8 }}
    {{ end }}
    template:
        metadata:
            annotations:
                reloader.stakater.com/match: "true"
                {{ if .Values.externalSecrets.projection.annotations }}
                {{ toYaml .Values.externalSecrets.projection.annotations | nindent 16 }}
                {{ end }}
            labels:
                {{ if .Values.externalSecrets.app.nameOverride }}
                name: {{ .Values.externalSecrets.app.name }}
                {{ else }}
                name: {{ .Values.externalSecrets.app.name }}-{{ .Values.externalSecrets.environment.name }}-secret
                {{ end }}
                {{ if .Values.externalSecrets.projection.labels }}
                {{ toYaml .Values.externalSecrets.projection.labels | nindent 16 }}
                {{ end }}
{{ end }}
