{{- $enabled_ing   := .Values.ing.enabled   }}

{{- if $enabled_ing }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  {{ if .Values.ing.namespaceOverride }}
  namespace: {{ .Values.ing.namespace }}
  {{ else }}
  namespace: {{ .Release.Namespace }}
  {{ end }}
  labels:
    {{ if .Values.ing.labels }}
    {{- range $name, $value := .Values.ing.labels }}
    {{- if not (empty $value) }}
    {{ $name }}: {{ $value }}
    {{- end }}
    {{- end }}
    {{ end }}
    name: {{ .Values.name }}
  annotations: 
    {{ if .Values.ing.annotations }}
    {{ toYaml .Values.ing.annotations | nindent 4 }}
    {{ end }}
spec:
  rules:
    {{ toYaml .Values.ing.config | nindent 4 }}
{{- end }}
