{{- $enabled_istio := .Values.istio.enabled }}

{{- if eq .Values.arch "istio-ing-svc-deployment-hpa" }}
  {{- $enabled_istio = true }}
{{- end }}

{{- if $enabled_istio }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- if .Values.labels }}{{- range $name, $value := .Values.labels }}{{- if not (empty $value) }}
    {{ $name }}: {{ $value }}
{{- end }}{{- end }}{{- else }}
    name: {{ .Values.name }}
{{- end }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation # TODO I dunno about this...
  servers:
  - port:
      number: 80 # Also not 100% sure on this
      name: http
      protocol: HTTP
    hosts:
{{- if .Values.ing.external_dns }}
    - "{{ .Values.ing.external_dns }}"
{{- end }}
{{- range $host := .Values.istio.hosts }}
    - "{{ $host }}"
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- if .Values.labels }}{{- range $name, $value := .Values.labels }}{{- if not (empty $value) }}
    {{ $name }}: {{ $value }}
{{- end }}{{- end }}{{- else }}
    name: {{ .Values.name }}
{{- end }}
spec:
  hosts:
{{- if .Values.ing.external_dns }}
    - "{{ .Values.ing.external_dns }}"
{{- end }}
{{- range $host := .Values.istio.hosts }}
  - "{{ $host }}"
{{- end }}
  gateways:
  - {{ .Values.name }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.port }}
        host: {{ .Values.name }}
{{- end }}
