{{- $enabled_pdb := .Values.pdb.enabled }}

{{- if $enabled_pdb }}
---
{{ if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{ else }}
apiVersion: policy/v1beta1
{{ end }}
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- if .Values.matchLabels }}{{- range $name, $value := .Values.matchLabels }}{{- if not (empty $value) }}
      {{ $name }}: {{ $value }}
      {{- end }}{{- end }}{{- else }}
      name: {{ .Values.name }}
  {{- end }}

{{- end }}
