{{- $enabled_secret := .Values.secret.enabled }}

{{- if $enabled_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- if .Values.labels }}{{- range $name, $value := .Values.labels }}{{- if not (empty $value) }}
    {{ $name }}: {{ $value }}
{{- end }}{{- end }}{{- else }}
    name: {{ .Values.name }}
{{- end }}
type: {{ .Values.secret.type }}
data:
{{- if .Values.secret.data }}{{- range $name, $value := .Values.secret.data }}{{- if not (empty $value) }}
  {{ $name }}: {{ $value }}
{{- end }}{{- end }}{{- else }}
  name: {{ .Values.name }}
{{- end }}{{- end }}
