{{- $enabled_serviceaccount := .Values.serviceAccount.enabled -}}

{{- if $enabled_serviceaccount -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}

  annotations: 
{{- if .Values.serviceAccount.annotations }}{{- range $name, $value := .Values.serviceAccount.annotations }}{{- if not (empty $value) }}
    {{ $name }}: {{ $value | quote }}
{{- end }}{{- end }}{{- end }}

  labels:
{{- if .Values.serviceAccount.labels }}{{- range $name, $value := .Values.serviceAccount.labels }}{{- if not (empty $value) }}
    {{ $name }}: {{ $value }}
{{- end }}{{- end }}{{- else }}
    name: {{ .Values.serviceAccount.name }}
{{- end }}

{{- end -}}
